.build_setup:
  stage: build
  image: docker:23.0.1
  services:
    - docker:23.0.1-dind
  interruptible: true
  allow_failure: false
  when: on_success
  tags:
    - docker
  before_script:
    echo $CI_GITHUB_TOKEN | docker login ghcr.io --username $CI_GITHUB_USER --password-stdin
  only:
    - main
    - /^deploy-.*$/

ruby-2.7.6:
  extends: .build_setup
  script:
    - ./build_push.sh 2.7.6

ruby-3.1.3:
  extends: .build_setup
  script:
    - ./build_push.sh 3.1.3
