.build_setup:
  stage: build
  image: docker
  variables:
    DOCKER_TLS_CERTDIR: ''
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  interruptible: true
  allow_failure: false
  when: on_success
  tags:
    - docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  only:
    - main

ruby-2.7.6:
  extends: .build_setup
  script:
    - ./build_push.sh 2.7.6
